hard_list = ['valetudinarian',
             'terpsichorean',
             'effulgent',
             'tatterdemalion',
             'funambulist',
             'succedaneum',
             'autochthonous',
             'appoggiatura',
             'verisimilitude',
             'autochthonous',
             'appoggiatura',
             'verisimilitude',
             'transmogrify',
             'antiestablishmentarianism',
             'pneumonoconiosis',
             'advantageous',
             'commensurateness',
             'xanthoma',
             'xanthophyll',
             'Zamiaceae',
             'Pneumonoultramicroscopicsilicovolcanoconiosis', ]  # yes that is a read word... good luck
